version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/project/crm-plugin
    steps:
      - checkout
      - run:
          name: Create Strapi project
          command: cd ~/project && yarn create strapi-app crm-project --quickstart --no-run
      - run:
          name: Reload the demo DB
          command: cp -R ~/project/crm-plugin/test/integration/testing_db/.tmp ~/project/crm-project/
      - run:
          name: Update configuration
          command: cp -R ~/project/crm-plugin/test/integration/testing_db/config/* ~/project/crm-project/config/
      - run:
          name: Install CRM plugin
          command: mkdir -p ~/project/crm-project/plugins && mv ~/project/crm-plugin ~/project/crm-project/plugins/
      - run:
          name: Start Strapi project
          #need to auto create admin user in strapi via command line before yarn start
          command: cd ~/project/crm-project && yarn start
      - run:
          name: Configure the plugin
          #need to update config file with correct credentials
          command: cp plugins/crm-plugin/tests/integration/config/config.js.sample plugins/crm-plugin/tests/integration/config/config.js
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
